### ISSUE TITLE
Impossible to run test or coverage tasks

### ISSUE THREAD

**Issue by RPDeshaies-playster** [fuse-box/angular2-example#11]
When I try to run `test` or `coverage` I get the following error

![image](https://cloud.githubusercontent.com/assets/24959029/22829081/b03092aa-ef6e-11e6-808e-09d672737382.png)

I'm using windows 7 and installed my dependencies using yarn.

**Comment by nchanged** [comment]
are you running `npm test`?
That is odd

**Comment by RPDeshaies** [comment]
Damn, I used the wrong Github account...

Here's my yarn log

```
λ yarn
yarn install v0.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "fuse-box@1.3.108" has unmet peer dependency "less@*".
warning "fuse-box@1.3.108" has unmet peer dependency "babel-core@*".
warning "fuse-box@1.3.108" has unmet peer dependency "stylus@*".
warning "fuse-box@1.3.108" has unmet peer dependency "uglify-js@*".
warning "fuse-box@1.3.108" has unmet peer dependency "source-map@*".
[4/4] Building fresh packages...
[1/2] ⠂ node-sass
[2/2] ⠂ contextify: not ok
[-/2] ⠄ waiting...
[-/2] ⠄ waiting...
error C:\Wks\ng2-fuse\node_modules\contextify: Command failed.
Exit code: 1
Command: C:\Windows\system32\cmd.exe
Arguments: /d /s /c node-gyp rebuild
Directory: C:\Wks\ng2-fuse\node_modules\contextify
Output:
C:\Wks\ng2-fuse\node_modules\contextify>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\Yarn\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.3.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files (x86)\Yarn\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files (x86)\Yarn\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at C:\Program Files (x86)\Yarn\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:111:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files (x86)\\Yarn\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Wks\ng2-fuse\node_modules\contextify
gyp ERR! node -v v7.3.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

```
λ npm test

> app@1.0.0 test C:\Wks\ng2-fuse
> TS_NODE_PROJECT=./src/tsconfig.mocha.json mocha  --opts ./test/mocha.opts -G

'TS_NODE_PROJECT' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
```

**Comment by suenot** [comment]
The same error in os x:
```
error /Users/suenot/ssdwork/angular2-example/node_modules/contextify: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /Users/suenot/ssdwork/angular2-example/node_modules/contextify
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@5.12.0 | darwin | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Users/suenot/anaconda/bin/python" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Users/suenot/.yarn/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Users/suenot/.yarn/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:193:7)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:323:11)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! stack     at Socket.emit (events.js:182:7)
gyp ERR! stack     at Pipe._onclose (net.js:484:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/Users/suenot/.nvm/versions/node/v5.12.0/bin/node" "/Users/suenot/.yarn/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/suenot/ssdwork/angular2-example/node_modules/contextify
gyp ERR! node -v v5.12.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
    at SpawnError (/Users/suenot/.yarn/lib/errors.js:18:1)
    at ChildProcess.<anonymous> (/Users/suenot/.yarn/lib/util/child.js:107:15)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:484:12)
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by suenot** [comment]
Error in python. Need to install python 2.

**Comment by RPDeshaies** [comment]
@suenot for me I fixed the first error by doing and I don't have python installed and it worked
``` 
npm rebuild node-sass
npm start
```

**Comment by RPDeshaies** [comment]
Other issue should be fixed by https://github.com/fuse-box/angular2-example/pull/15

**Comment by ojacquemart** [comment]
@suenot @RPDeshaies Could you retry? #15 was fixed

**Comment by RPDeshaies** [comment]
@ojacquemart will try on monday ! :)
