### ISSUE TITLE
Page stuck at "Loading..."

### ISSUE THREAD

**Issue by sivabudh** [fuse-box/angular2-example#12]
I did `npm install` followed by `npm start` and this is what I got on the terminal:

```
 ~/C/angular2-example npm start                                                                                                                                                              master ✱

> fusebox-angular@1.0.0 start /Users/Pac/Code/angular2-example
> node ./fuse.js

15:50:18 : Launching dev server on port 4445
Error: ENOENT: no such file or directory, scandir '/Users/Pac/Code/angular2-example/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (/Users/Pac/Code/angular2-example/node_modules/node-sass/lib/extensions.js:122:13)
    at foundBinariesList (/Users/Pac/Code/angular2-example/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/Pac/Code/angular2-example/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/Pac/Code/angular2-example/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/Pac/Code/angular2-example/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/Pac/Code/angular2-example/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

and from the browser when I access `localhost:4445` all I see is just: `Loading...` in plain text.

Is this expected?

**Comment by nchanged** [comment]
You have some problems with your NodeJs/NPM installation. Sass can't get compiled. Do you have any other alternative methods of launching it?

**Comment by arabsight** [comment]
I had the same issue, I installed node-sass@4.5.0, then disabled the cache in FuseBox.init. I don't know what the issue is but that worked.

**Comment by nchanged** [comment]
It might be missing in package.json I will check it!

**Comment by nchanged** [comment]
Also removing .fuse-box usually helps :) try that and enable caching

**Comment by devmondo** [comment]
@sivabudh @arabsight this is a well known `node-sass` issue, especially if you are on windows, to fix it do the following:
run `npm rebuild node-sass`
delete `fusebox` cache folder
run `npm start` 

after that all should be fine, I faced exactly your issue and after doing the above, everything works fine now and I can see the example running in the browser :)

please let us know

**Comment by arabsight** [comment]
yep, that's it, working great, thanks.

**Comment by sivabudh** [comment]
Finally, @devmondo. Thank you so much. Your suggestion actually made sense, actionable, and best of all, it worked!!!

I knew it had nothing to do with NodeJS/NPM installation because I can run all other projects with Webpack fine.

Amazing!
