### ISSUE TITLE
Test fail with compile TS error

### ISSUE THREAD

**Issue by rajinder-yadav** [fuse-box/angular2-example#17]
When I run test it fail with the following error:

```sh
angular2-example: fix-13-breaks-on-npm-install$ npm t

> fusebox-angular@1.0.0 test /tmp/fix/angular2-example
> set TS_NODE_PROJECT=./src/tsconfig.mocha.json&& mocha  --opts ./test/mocha.opts -G


TSError: ⨯ Unable to compile TypeScript
src/app.component.ts (7,14): Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning. (1219)
    at getOutput (/tmp/fix/angular2-example/node_modules/ts-node/src/index.ts:319:17)
    at /tmp/fix/angular2-example/node_modules/ts-node/src/index.ts:350:18
    at Object.compile (/tmp/fix/angular2-example/node_modules/ts-node/src/index.ts:483:19)
    at Module.m._compile (/tmp/fix/angular2-example/node_modules/ts-node/src/index.ts:413:44)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/tmp/fix/angular2-example/node_modules/ts-node/src/index.ts:416:12)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /tmp/fix/angular2-example/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/tmp/fix/angular2-example/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/tmp/fix/angular2-example/node_modules/mocha/lib/mocha.js:487:10)
    at loadAndRun (/tmp/fix/angular2-example/node_modules/mocha/bin/_mocha:416:22)
    at Object.<anonymous> (/tmp/fix/angular2-example/node_modules/mocha/bin/_mocha:433:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**Comment by nchanged** [comment]
Same here
```
TSError: ⨯ Unable to compile TypeScript
src/app.component.ts (7,14): Experimental support for decorators is a feature that is
subject to change in a future release. Set the 'experimentalDecorators' option to remo
ve this warning. (1219)
```
Any ideas?

**Comment by ojacquemart** [comment]
On linux, with the following test script, the typescript compiles

`"test": "TS_NODE_PROJECT=./src/tsconfig.mocha.json mocha --opts ./test/mocha.opts -G",`

But I got another error:

```
  1) TodoListComponent calls service to get todos:
     Error: Error in ./TodoListComponent class TodoListComponent - inline template:16:60 caused by: Cannot read property 'add' of undefined
      at ViewWrappedError.Error (native)
      at ViewWrappedError.ZoneAwareError (/home/olivier/dev/workspaces/angular2/angular2-example/node_modules/zone.js/dist/zone.js:958:33)
```

**Comment by nchanged** [comment]
@ojacquemart could you suggest a fix?

**Comment by ojacquemart** [comment]
With the following modifications, tests pass:

package.json
`"test": "TS_NODE_PROJECT=./src/tsconfig.mocha.json mocha --opts ./test/mocha.opts -G",`

and mocha.shim.js
`var jsdom = require('jsdom')`

But it should not work on windows.

**Comment by nchanged** [comment]
Ok then, can we have 2 scripts then? for windows and for *nix?

**Comment by ojacquemart** [comment]
We could use https://www.npmjs.com/package/cross-env

PR is coming :)

**Comment by ojacquemart** [comment]
It should be tested by a windows dev but it should work regarding the lib popularity :)

**Comment by rajinder-yadav** [comment]
This was too eagerly closed, I am still seeing errors, should I create a new issue or can you reopen this please?

**Comment by rajinder-yadav** [comment]
I've created a new issue, please don't close before by the originator has has a say, at least wait a few days.
