### ISSUE TITLE
Does not start after npm install. Error in HTMLplugin

### ISSUE THREAD

**Issue by yaroslavya** [fuse-box/angular2-example#2]
I made a fresh `git clone` and `npm install`. Then installed gulp. then ran `gulp start` .
Then I had the following error: 
"SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode"
Fixed by adding "use strict"; to the top of the `gulpfile.js`
Tried `gulp start` again, it resulted in the following error:

C:\angular2-example\node_modules\fuse-box\dist\commonjs\plugins\HTMLplugin.js:3
    constructor(opts = {}) {
                     ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Programming\github\angular2-example\node_modules\fuse-box\dist\commonjs\index.js:10:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

Not sure what am I doing wrong. Tried on both Windows7 and Windows8. Npm version= 3.8.6
Node version:  4.2.1

**Comment by nchanged** [comment]
Hi!
Thanks for the issue. It's related to the `NodeJS` version. The thing is version `4.2.1` (which will be soon deprecated) requires "use-strict" for each file using classes. 

Consider upgrading your NodeJS version.
In the meantime, i will check what i can do to make it work with older NodeJS versions
Cheers

**Comment by yaroslavya** [comment]
Thanks for the quick reply, @nchanged . Just upgraded to the latest nodejs and it worked at once.
So you can close the issue as 4.2.1 is really old. Thanks for the help again! :+1:

**Comment by nchanged** [comment]
Any time!
Cheers
