### ISSUE TITLE
not fusing with current beta 16

### ISSUE THREAD

**Issue by Tenvan** [fuse-box/angular2-example#32]
Hi,
project doesnt fusing since beta 16:
'Cannot read property 'entryFile' of undefined'

```
vendor ->
app ->
→Typescript config:  \src\tsconfig.json
→Typescript config:  \src\tsconfig.json
└──  (13 files,  45.9 kB) default
     main.js
     main.scss
     app.module.js
     app.component.js
     todo/todo-filter.pipe.js
     todo/todo-item.component.js
     todo/todo.model.js
     todo/todo-item.component.html
     todo/todo-item.component.css
     todo/todo-list.component.js
     todo/todo.service.js
     todo/todo-list.component.html
     todo/todo-list.component.css
Size: 45.9 kB in 1s 187ms
TypeError: Cannot read property 'entryFile' of undefined
    at Function.onNode (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\analysis\plugins\OwnBundle.js:13:28)
    at plugins.forEach.plugin (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\analysis\FileAnalysis.js:78:80)
    at Array.forEach (native)
    at pre (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\analysis\FileAnalysis.js:78:55)
    at visit (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\ASTTraverse.js:18:23)
    at Function.traverse (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\ASTTraverse.js:41:9)
    at FileAnalysis.analyze (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\analysis\FileAnalysis.js:77:35)
    at File.makeAnalysis (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\core\File.js:146:23)
    at File.consume (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\core\File.js:172:22)
    at info.bundleData.including.forEach (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\core\ModuleCollection.js:119:30)
└──  (0 files,  53 Bytes) default
Size: 53 Bytes in 2s 930ms
TypeError: Cannot read property 'entryFile' of undefined
    at Function.onNode (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\analysis\plugins\OwnBundle.js:13:28)
    at plugins.forEach.plugin (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\analysis\FileAnalysis.js:78:80)
    at Array.forEach (native)
    at pre (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\analysis\FileAnalysis.js:78:55)
    at visit (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\ASTTraverse.js:18:23)
    at Function.traverse (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\ASTTraverse.js:41:9)
    at FileAnalysis.analyze (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\analysis\FileAnalysis.js:77:35)
    at new ComponentContext (D:\Node\Recherche\fuse-box-angular2-example\node_modules\ng2-fused\dist\components\component-context.js:31:27)
    at Ng2TemplatePluginClass.transform (D:\Node\Recherche\fuse-box-angular2-example\node_modules\ng2-fused\dist\plugins\ng2-template-plugin.js:34:32)
    at tasks.push (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\core\File.js:122:59)

---------------------------------------------------
Development server running http://localhost:4445
---------------------------------------------------

07:48:47: HMR is enabled
```

**Comment by nchanged** [comment]
Thanks I will take a look, please drop back to the recent stable release 2.0.2

**Comment by Tenvan** [comment]
same error with 2.0.2 (see below), but we need anyway the 2.1 for fusing material and covalent...

```
vendor -> 


app -> 

  → Typescript config:  \src\tsconfig.json
  → Typescript config:  \src\tsconfig.json
TypeError: Cannot read property 'entryFile' of undefined
    at Function.onNode (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\analysis\plugins\OwnBundle.js:13:28)
    at plugins.forEach.plugin (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\analysis\FileAnalysis.js:78:80)
    at Array.forEach (native)
    at pre (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\analysis\FileAnalysis.js:78:55)
    at visit (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\ASTTraverse.js:18:23)
    at Function.traverse (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\ASTTraverse.js:41:9)
    at FileAnalysis.analyze (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\analysis\FileAnalysis.js:77:35)
    at File.makeAnalysis (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\core\File.js:146:23)
    at File.consume (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\core\File.js:172:22)
    at info.bundleData.including.forEach (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\core\ModuleCollection.js:119:30)
└── default (0 files,  53 Bytes)

    Size: 53 Bytes in 4s 440ms
(node:8704) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'entryFile' of undefined
(node:8704) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
└── default (13 files,  45.9 kB)
      main.js
      main.scss
      app.module.js
      app.component.js
      todo/todo-filter.pipe.js
      todo/todo-item.component.js
      todo/todo.model.js
      todo/todo-item.component.html
      todo/todo-item.component.css
      todo/todo-list.component.js
      todo/todo.service.js
      todo/todo-list.component.html
      todo/todo-list.component.css

    Size: 45.9 kB in 4s 479ms

---------------------------------------------------
Development server running http://localhost:4445
---------------------------------------------------

08:31:48 : HMR is enabled
```

**Comment by nchanged** [comment]
What about 2.0.1 ?

**Comment by nchanged** [comment]
If it doesn't that means something is broken with your build - 2.0.1 should be working 100%

**Comment by nchanged** [comment]
Just pushed the version bump. Works perfectly for me, try cloning the repository from scratch and run it again.

**Comment by Tenvan** [comment]
hm.. strange... it seems to be again an yarn problem... 
i have installed the fixed version 2.0.2 without '^' and it doesnt work.
after that reverted to your last bumped version with '^2.0.2' and install with 'npm install' without cleaning node_modules.
now it works with npm AND yarn... :/ and version 2.0.12... very strange

**Comment by nchanged** [comment]
Yeah yarns installs the latest tag regardless if it's beta or not. There might an issue of order. With 2.1.0 should be all resolved. As for me, i am using npm4 `npm5` fails badly on me

**Comment by Tenvan** [comment]
i found now the problem:
the 'rectangular' package makes troubles again...
in earlier versions you have provide the workaround

``` 
fuse.register('rectangular', { homeDir: 'node_modules/rectangular', main: 'index.js', instructions: '**/**.js' });
```

but this produces the 'entryFile' error.
without this entry fusing works, but not so the app. 
you get than gain the error with missing 'rectangular' classes...

see on my fork in develop-branch: https://github.com/Tenvan/angular2-example

**Comment by nchanged** [comment]
```js
fuse.register('rectangular', { homeDir: 'node_modules/rectangular', main: 'index.js', instructions: '**/**.js' });
```
Like that maybe? Please submit an issue to fuse-box repository, so we won't forget.

**Comment by nchanged** [comment]
And upgrade to 2.1.0 (the example is updated)

**Comment by Tenvan** [comment]
yes, like that.. that was an formating error in the issue... i have fixed it..
and yes, fuse-box is upgraded to 2.1.0.
