### ISSUE TITLE
TypeScript related error when trying to run

### ISSUE THREAD

**Issue by benjamincombes** [fuse-box/angular2-example#33]
Hi, when trying to run the example following provided instruction, I get the following error:
```
TypeError: Cannot read property 'onTypescriptTransform' of undefined
    at context.plugins.forEach (/Users/benjamincombes/Downloads/angular2-example-master 2/node_modules/fuse-box/dist/commonjs/core/File.js:85:58)
    at Array.forEach (native)
    at File.tryTypescriptPlugins (/Users/benjamincombes/Downloads/angular2-example-master 2/node_modules/fuse-box/dist/commonjs/core/File.js:84:34)
    at File.handleTypescript (/Users/benjamincombes/Downloads/angular2-example-master 2/node_modules/fuse-box/dist/commonjs/core/File.js:233:14)
    at File.consume (/Users/benjamincombes/Downloads/angular2-example-master 2/node_modules/fuse-box/dist/commonjs/core/File.js:167:25)
    at ModuleCollection.resolve (/Users/benjamincombes/Downloads/angular2-example-master 2/node_modules/fuse-box/dist/commonjs/core/ModuleCollection.js:176:18)
    at realm_utils_1.each (/Users/benjamincombes/Downloads/angular2-example-master 2/node_modules/fuse-box/dist/commonjs/core/ModuleCollection.js:59:25)
    at iterateMap (/Users/benjamincombes/Downloads/angular2-example-master 2/node_modules/realm-utils/dist/commonjs/each.js:43:34)
    at /Users/benjamincombes/Downloads/angular2-example-master 2/node_modules/realm-utils/dist/commonjs/each.js:59:17
    at /Users/benjamincombes/Downloads/angular2-example-master 2/node_modules/realm-utils/dist/commonjs/each.js:63:14
```

I just downloaded the zip, ran `npm install` and `npm start`.
I have node v8.1.2, npm v5.0.3; any idea of what can cause this? Let me know if I can give any useful information.

**Comment by nchanged** [comment]
hi @benjamincombes which fusebox version are you using?

**Comment by nchanged** [comment]
I confirm, that's a bug, I will release a hotfix right away

**Comment by benjamincombes** [comment]
Hi @nchanged, I just did npm install, so it is version 2.1.0 ; are you having the bug too?

**Comment by nchanged** [comment]
Thanks @benjamincombes for catching it, such a shame from our end.
`fuse-box@2.2.0-beta.1`

**Comment by benjamincombes** [comment]
Thanks, it works now :) !
